PRAGMA foreign_keys = ON;

    DROP TABLE IF EXISTS buildings;

    CREATE TABLE buildings(
        id INTEGER, abbr TEXT NOT NULL, addr TEXT NOT NULL, descrip TEXT NOT NULL, building_prose TEXT NOT NULL, total_rating INTEGER NOT NULL, n_ratings INTEGER NOT NULL,
        PRIMARY KEY(id));

INSERT INTO buildings VALUES(0, "HQ","320 YORK STREET, NEW HAVEN, CT, 06511","HUMANITIES QUADRANGLE", "Was completed in 1932 with funds provided by the trustees of the estate of John W. Sterling, BA 1864. The building, Collegiate Gothic with modernistic Arts & Craft and Art Nouveau touches, is of brick and seam-faced granite with limestone trim.  James Gamble Rogers was the architect. The use of various interconnected low buildings, grouped around two courts with a central fourteen-story tower was characteristic of Rogers conscious effort to create urban compositions. The Hall was designed to be self-contained.  It includes dormitory accommodations for students, faculty apartments, and classrooms, lecture halls, faculty offices, dining hall and common rooms. The office of the Provost is also located here.. In 1993 accessibility ramps were built at the main entrance, and in 1997, the McDougal  --                                                                           . [320 York Street] Main Campus [ 5.10]", 0.0, 0);
INSERT INTO buildings VALUES(1, "PWG","70 TOWER PARKWAY, NEW HAVEN, CT, 06511","PAYNE WHITNEY GYM", "Completed in 1932, is a memorial to Payne Whitney, BA 1898, the gift of his wife and his children, Mrs. Charles Shipman Payson and John Hay Whitney, BA 1926, MA HON 1956. The building is Gothic, constructed of Briar Hill sandstone. This second- largest athletic facility in the world boast twelve acres of floor space on sixteen levels. The central portion contains rowing tanks, practice pool, locker rooms, basketball courts, rooms for boxing, wrestling, and fencing, the trophy room, and offices. In the northern wing are squash courts, a running track, and a basketball amphitheatre. The southern wing contains the exhibition pool and handball courts. Architect John Russell Pope designed the structure to accommodate the then 3,500 students then attending Yale College. A  sports rehabilitation center was built into the gym in 1994, as well as the start of a comprehensive restoration and renovation. The building will be extensively altered and wings added. The architect is Ellerbe Becket Architects in Collaboration with Cesar Pelli & Associates. In 1995, the John J. Lee Amphitheatre was named in honor of John L. Lee ‘58 E, ‘59 M.Eng. a star basketball player in his college days, Mr. Lee gave generously in support of the gym. In 1996, six new international sized squash courts were constructed, replacing eight existing U.S. format courts. Colonel  William K. Lanman, Sheffield Scientific School class of 28 is the donor of a large new wing designed to accommodate four basketball/ volleyball courts and an elevated indoor track  scheduled to be in use in 1999. By the office of Cesar Pelli.  [70 Tower Parkway", 0.0, 0);
INSERT INTO buildings VALUES(2, "BASSLB","110 WALL STREET, NEW HAVEN, CT, 06511","BASS LIBRARY", "Is a two-story facility with reference & reserve book stacks, extensive student reading & study space. Immediately underneath the Cross-Campus Plaza, It connects to the Sterling Memorial Library by tunnel under High Street. The direct entrances to the library lead down to light courts from the lawn that forms the library’s roof. The architect was Edward Larabee Barnes.  In 1986, matching pavilions were built above ground. One is an elevator affording access to the library by disabled patrons, and the other houses mechanical equipment. [119 High St]  Cross Campus -Main Campus[ 9.36]", 0.0, 0);
INSERT INTO buildings VALUES(3, "SC","168 GROVE STREET, NEW HAVEN, CT, 06511","SCHWARZMAN CENTER", "Is the north wing of the L-shaped Bicentennial Building erected in 1901 to commemorate the 200th anniversary of the founding of the collegiate school (funds from the alumni). The building is of Indiana limestone and was designed by Carrere & Hastings. This wing, built as Commons for the entire college, is now the freshman dining hall and cafeteria for faculty and staff. It seats 1,200. The other wing, Woolsey Hall, is an auditorium seating 2,700 (see Woolsey Hall).  Memorial Hall is the central circular central building with a domed rotunda; the formal  entrance for the two wings. It contains tablets commemorating Yale men who died in the War of the Revolution, the Civil War, the Spanish American War, the World Wars, Korea, and Vietnam, as well as other memorial plaques, is mounted in the corridors.  The President’s Room on the second floor is used for official functions. For many years the Steinert Collection of Musical Instruments was exhibited on the third floor that now houses recording studios. The Alumni War Memorial, designed by Thomas Hastings in collaboration with Everett V. Meeks, forms a classical colonnade on the south side of the dining hall. It  was dedicated June 19, 1917, as a tribute to Yale men who died in World War I.  The entablature bears the names of the major battles in which American troops fought and a cenotaph in front completes the memorial. [College/ Grove Streets]  Hewitt Quadrangle", 0.0, 0);
INSERT INTO buildings VALUES(4, "ML","9 HILLHOUSE AVENUE, NEW HAVEN, CT, 06511","MASON LAB", "Formerly the Mason Laboratory of Mechanical Engineering, completed in 1911, was the gift of William Smith Mason, PH.B. 1888, MA HON. 1924, and George Grant Mason, PH.B. 1888. HON. 1922. The Trustees of the Sheffield Scientific School had purchased the site in 1901. Fronting on Hillhouse Avenue, the building extends through to Temple Street where there is provision for delivery of heavy machinery. A three-story brick building with Indiana limestone facade, it was equipped with facilities for the investigation of engineering systems involving thermodynamics, fluid mechanics, heat transfer, combustion, kinematics, dynamics of machines, physics of fluids, and the mechanics of materials. Charles C. Haight was the architect. It was extensively remodeled in 1967 to provide classroom, office, and laboratory facilities for the Department of Engineering and Applied Science. [9 Hillhouse Avenue]", 0.0, 0);
INSERT INTO buildings VALUES(5, "AKW","51 PROSPECT STREET, NEW HAVEN, CT, 06511","A.K. WATSON HALL", "Formerly the Sheffield Laboratory of Engineering Mechanics, is a four-story brick Romanesque Revival building, trimmed with terra cotta and East Haven sandstone, which was erected in 1894-95 as the Sheffield Chemical Laboratory. Cady, Berg & See were the architects. Following the completion of the Sterling Chemistry Laboratory it was remodeled in 1923 and the name changed. Besides classroom facilities for the School of Engineering, offices were provided for the Army Reserve Officers Training Corps and the national headquarters of the Society of Sigma Xi and the Scientific Research Society of America. Between 1969 and 1973 the rooms were used by the School of Music for classroom, studio and instrument practice facilities. A comprehensive restoration and renovation was undertaken in 1984/85 for Computer Science Department. Roth and Moore was the architectural firm.[51 Prospect Street] –", 0.0, 0);
